### ISSUE TITLE
Does not throw error for invalid browser.json

### ISSUE THREAD

**Issue by aniruddh-a** [lasso-js/lasso#155]
Not showing any error related to unexpected characters / invalid JSON config.

Invalid json config - browser.json :

[ { "type": "js", "url": "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js" }, ]

Error shown after some time :

Error: Async fragment failed (lasso-slot:head). Exception: Error: Async fragment (lasso-slot:head) timed out after 30000ms

I believe a parsing error can be thrown right away if browser.json or any other config file is invalid and lasso is unable to parse such file.

Error log:
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Async fragment failed (lasso-slot:head). Exception: Error: Async fragment (lasso-slot:head) timed out after 30000ms
    at Timeout._onTimeout (/Users/aadkar/Aniruddh/eBay/sample_getting_started/nodash-with-dep-tracker/telemetry-node/node_modules/marko/node_modules/async-writer/src/AsyncWriter.js:344:29)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at AsyncWriter.error (/Users/aadkar/Aniruddh/eBay/sample_getting_started/nodash-with-dep-tracker/telemetry-node/node_modules/marko/node_modules/async-writer/src/AsyncWriter.js:434:13)
    at Timeout.<anonymous> (/Users/aadkar/Aniruddh/eBay/sample_getting_started/nodash-with-dep-tracker/telemetry-node/node_modules/marko/node_modules/async-writer/src/AsyncWriter.js:344:23)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)`

**Comment by nguyenpc** [comment]
Hi there, is there any update on this issue? I'm only got this issue some time at first access after deployed to the server. but I'm not sure if this bug will happen again in the future in production site.
