### ISSUE TITLE
lasso/middleware & koa v2

### ISSUE THREAD

**Issue by basickarl** [lasso-js/lasso#161]
https://github.com/koajs/koa

I peeked in the middleware.js file and see that it's been made to comply with express. I tweaked my own version and is working. Just want you to know this!

working for koa (lass/middleware/serveStatic.js):
```
    // line 44
    return function(ctx, next) {
        var req = ctx.request,
            res = ctx.response;
```

**Comment by basickarl** [comment]
Another issue has popped up, when requiring the middleware with the following:

`import lasso_middleware from 'lasso/middleware/koa';`

The following error:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'lasso/middleware/koa'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/karl/dev/sketch/experiment/koa-babel-lasso/src/index.js:13:1)
    at Module._compile (module.js:541:32)
    at loader (/home/karl/dev/sketch/experiment/koa-babel-lasso/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/karl/dev/sketch/experiment/koa-babel-lasso/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

Fixed it with including a file in the middleware/koa directory `index.js` with the following contents:

`exports.serveStatic = require('./serveStatic');`

This has also further down the line had issues with the `send` module, discussed here: https://github.com/pillarjs/send/issues/117

This was fixed by using the original node req and res objects instead.

There was also a problem with `require('../')` since it's one level deeper I just changed it to `require('../../')`. I changed the `serverStatic.js` file to instead send the original node.js objects `ctx.res` and `ctx.req` to the send module (as I stated before), here is the new file:

```
require('raptor-polyfill/string/startsWith');
require('raptor-polyfill/string/endsWith');

var lasso = require('../../');
var send = require('send');
var extend = require('raptor-util/extend');

function notFound() {
    this.error(404);
}

module.exports = function(options) {
    options = options || {};

    var myLasso = options.lasso || lasso.getDefaultLasso();
    var config = myLasso.config;

    var outputDir = config.outputDir;
    var urlPrefix = config.urlPrefix;
    var routePrefix = urlPrefix;
    if (!routePrefix.endsWith('/')) {
        routePrefix += '/';
    }

    if (!outputDir || !urlPrefix) {
        return function(req, res, next) {
            return next();
        };
    }

    var sendOptions = {
        fallthrough: false,
        redirect: false,
        index: false
    };

    if (options.sendOptions) {
        extend(sendOptions, options.sendOptions);
    }

    sendOptions.root = outputDir;


    return function(ctx, next) {
        var req = ctx.request,
            res = ctx.response;

        var path = req.path;
        if (!path.startsWith(routePrefix) || (req.method !== 'GET' && req.method !== 'HEAD')) {
            return next();
        }

        var filePath = path.substring(routePrefix.length);

        // create send stream
        var stream = send(ctx.req, filePath, sendOptions);

        // add directory handler
        stream.on('directory', notFound);

        // forward errors
        stream.on('error', function error(err) {
            console.log(err);
            ctx.res.statusCode = err.statusCode || 500;
            ctx.res.end('Not found: ' + filePath);
        });

        // pipe
        stream.pipe(ctx.res);
    };
};

```

Now when trying to render a marko template it downloads the html instead of displaying it. Following koa code:

```
'use strict';

// import npm modules
import Koa from 'koa'; // koa framework
import KoaRouter from 'koa-router';
import lasso from 'lasso'; // lassojs
import lasso_middleware from 'lasso/middleware/koa';
import marko_nodeRequire from 'marko/node-require'; // marko template engine

// setup
const app = new Koa(); // new instance
marko_nodeRequire.install(); // marko requires this

// configure lasso
lasso.configure({
    require: {
        transforms: [{
            transform: "lasso-babel-transform",
            config: {
                extensions: [
                    ".js",
                    ".es6"
                ]
            }
        }]
    },
    bundlingEnabled: false,
    fingerprintsEnabled: false,
    minify: false
});

// add file serving middleware
app.use(lasso_middleware.serveStatic());

const router = new KoaRouter();
router.get(`/`, async function(ctx, next) {
    ctx.type = 'text/html; charset=utf-8'; // <--- without this the file downloads

    var template = require('src/marko/layouts/base/base.marko');
    ctx.body = template.stream({
        press: 'press'
    });

});
app.use(router.routes());

// listen to port
app.listen(3000, function() {
    console.log('listening to port 3000');
});
```

Without the `ctx.type = 'text/html; charset=utf-8';` line, the file downloads. When I include it the following error happens:

```
{ Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/send/index.js:326:13)
    at SendStream.send (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/send/index.js:530:17)
    at onstat (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/send/index.js:629:10)
    at FSReqWrap.oncomplete (fs.js:117:15) expose: false, statusCode: 500, status: 500 }
send index.js: text/plain; charset=utf-8
```

This error is from the send module as seen in the stack trace. Since I am setting the content-type in koa this seems to be messing with how the send module is working? Any ideas?

**Comment by basickarl** [comment]
Currently:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'lasso/middleware/koa'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/src/index.js:7:1)
    at Module._compile (module.js:570:32)
    at loader (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```
I've fully fixed this now, tested on both koa and koa@2. Here is the pull request.

https://github.com/lasso-js/lasso/pull/169

**Comment by basickarl** [comment]
Currently fixing the send module so that it works with both versions of koa, once that is fixed I'll update lasso. 
https://github.com/pillarjs/send/pull/120#pullrequestreview-4870245 
https://github.com/pillarjs/send/issues/118
