### ISSUE TITLE
Caused by: Error: Module not found: C:UserskarlDocumentsDevelopmentlanguramaapplicationclientcomponentsapp__sign-inindex.marko 

### ISSUE THREAD

**Issue by basickarl** [lasso-js/lasso#279]
```
        "@lasso/marko-taglib": "^1.0.10",
        "marko": "^4.1.2",
        "lasso": "^2.11.6",
        "lasso-babel-transform": "^1.0.2",
        "lasso-marko": "^2.3.0",
```
Running on Windows (I'm guessing this might be the issue). Somethings fishy here:
```

  Error: Render async fragment error (lasso-slot:head). Exception: Error: Failed to walk dependency [require: C:\Users\karl\Documents\Development\langurama\application\client\pages\sign-in\index.marko.js.init.js]. Dependency chain: [require: C:\Users\karl\Documents\Development\langurama\application\client\pages\sign-in\index.marko.js.init.js]. Cause: Error: Module not found: C:UserskarlDocumentsDevelopmentlanguramaapplicationclientcomponentsapp__sign-inindex.marko (from "application\client\pages\sign-in" and referenced in "application\client\pages\sign-in\index.marko.js.init.js")
      at module.exports (C:\Users\karl\Documents\Development\langurama\node_modules\raptor-util\createError.js:7:50)
      at AsyncValue.<anonymous> (C:\Users\karl\Documents\Development\langurama\node_modules\lasso\lib\dependency-walker.js:141:48)
      at notifyCallbacks (C:\Users\karl\Documents\Development\langurama\node_modules\raptor-async\AsyncValue.js:76:35)
      at AsyncValue.reject (C:\Users\karl\Documents\Development\langurama\node_modules\raptor-async\AsyncValue.js:240:9)
      at getDependenciesCallback (C:\Users\karl\Documents\Development\langurama\node_modules\lasso\lib\dependencies\Dependency.js:373:47)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  Caused by: Error: Module not found: C:UserskarlDocumentsDevelopmentlanguramaapplicationclientcomponentsapp__sign-inindex.marko (from "application\client\pages\sign-in" and referenced in "application\client\pages\sign-in\index.marko.js.init.js")
      at handleRequire (C:\Users\karl\Documents\Development\langurama\node_modules\lasso-require\src\inspect-cache.js:35:23)
      at Array.map (<anonymous>)
      at resolveInspectedRequires (C:\Users\karl\Documents\Development\langurama\node_modules\lasso-require\src\inspect-cache.js:46:61)
      at afterInspect (C:\Users\karl\Documents\Development\langurama\node_modules\lasso-require\src\inspect-cache.js:109:9)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
      at AsyncStream.error (C:\Users\karl\Documents\Development\langurama\node_modules\marko\dist\runtime\html\AsyncStream.js:425:13)
      at module.exports.lassoPageResultAsyncValue.done.process.nextTick (C:\Users\karl\Documents\Development\langurama\node_modules\lasso\taglib\slot-tag.js:106:30)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
It seems weird the module name:
```
 Caused by: Error: Module not found: C:UserskarlDocumentsDevelopmentlanguramaapplicationclientcomponentsapp__sign-inindex.marko 
```
Any ideas?

**Comment by basickarl** [comment]
Updated the packages as they were lacking in version^^.
