### ISSUE TITLE
Can't work well in windows

### ISSUE THREAD

**Issue by shijunjuan** [lasso-js/lasso#65]
I try to following the guide to write a sample, but got below error:
Error: Dependency of type "C" is not supported. (dependency={ type: 'C', path: '/cygwin64/home/junjshi/sample/main.js' }, package="undefined"). Registered types:
css, js, comment, loader-metadata, package, intersection, commonjs-def, commonjs-run, commonjs-dep, commonjs-main, commonjs-remap, commonjs-resolved, commonjs-ready, commonjs-search-path, require
    at Object.DependencyRegistry.createDependency (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:421:19)
    at C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:506:45
    at applyNextNormalizer (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:441:24)
    at applyNextNormalizer (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:467:17)
    at applyNextNormalizer (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:467:17)
    at C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:458:21
    at globNormalizer (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\glob.js:55:9)
    at applyNextNormalizer (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:447:17)
    at Object.DependencyRegistry._normalizeDependency (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:471:9)
    at normalizeNext (C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\lib\dependencies\DependencyRegistry.js:494:19)

I was using cygwin on windows.
So I have to change C:\Users\junjshi\AppData\Roaming\npm\node_modules\lasso-cli\node_modules\lasso\node_modules\lasso-require\lib\util\parseRequire.js

Line 3:
if (typeSeparatorIndex !== -1 && !process.platform.startsWith("win")) {

**Comment by patrick-steele-idem** [comment]
That does sound like a bug. I'm taking a look at it and hopefully will have a fix soon. I don't use Windows so I'll probably need your help verifying the fix. Thanks for creating the Github issue!
